In [21]:
import numpy as np
# Creación de un array 1D partiendo de una lista
array = np.array([1, 2, 3, 4, 5])
print(array)
print(type(array))
print(array.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [22]:
# Asignaciones
array[0] = 0
print(array)


[0 2 3 4 5]


In [23]:
# Arrays multidimensionales
# 3 filas 4 colunas
marray = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
print(marray)
print(marray.shape)


[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
(3, 4)


In [24]:
# Tipos de datos.
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr2 = np.array([1, 2, 3], dtype = np.int32)
print(arr1.dtype)


float64


In [25]:
# Casteo de arrays.
arr = np.array([1,2,3,4])
print(arr.dtype)
arr = arr.astype(np.float64)
print(arr.dtype)


int32
float64


In [26]:
# Inicialización arrays con zeros
a = np.array([[1,2], [3,4]], dtype = complex)
a = np.zeros((2,2)) 
print(a)


[[0. 0.]
 [0. 0.]]


In [27]:
# Inicialización arrays vacio.
a = np.empty((2,3))
print(a)

[[4.24399158e-314 8.48798317e-314 1.06099790e-313]
 [1.48539705e-313 1.69759663e-313 2.12199579e-313]]


In [28]:
# Inicialización array con 1 en la diagonal
a = np.eye(3)
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
# Crear secuencias de números.
print(np.arange(10,30,5))

[10 15 20 25]


In [30]:
# Indexación y slicing
arr1d = np.arange(10)
print(arr1d)
print(arr1d[5])
print(arr1d[5:7]) #slicing

arr1d[5:7] =13
print(arr1d)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6]
[ 0  1  2  3  4 13 13  7  8  9]
